#!/bin/bash
#PBS -l nodes=1:ppn=4
#PBS -l mem=32gb
#PBS -l walltime=12:00:00
set -e

# Make output directory
mkdir -p out_dir
mkdir -p html_report

# Moderate parallelism
# Prevent from creating too many threads to avoid an Out Of Memory (OOM) error in Brainlife
export OMP_NUM_THREADS=4
export OPENBLAS_NUM_THREADS=4
export MKL_NUM_THREADS=4
export NUMEXPR_NUM_THREADS=4
export VECLIB_MAXIMUM_THREADS=4
export SINGULARITYENV_OMP_NUM_THREADS=4
export SINGULARITYENV_OPENBLAS_NUM_THREADS=4
export SINGULARITYENV_MKL_NUM_THREADS=4
export SINGULARITYENV_NUMEXPR_NUM_THREADS=4
export SINGULARITYENV_VECLIB_MAXIMUM_THREADS=4

# Force PyVista/VTK to use a virtual GPU
 
export SINGULARITYENV_QT_QPA_PLATFORM="offscreen"
export SINGULARITYENV_PYVISTA_OFF_SCREEN="true"
export SINGULARITYENV_MPLBACKEND="Agg"
 
export SINGULARITYENV_DISPLAY=":99"
export SINGULARITYENV_QT_QPA_PLATFORM="offscreen"
 
# Own image (uploaded to GitHub)
singularity exec -e docker://ghcr.io/carlota-juarez/app-mne-bids@sha256:4c8c305c927b9b876b2d6216af0c70cd4de2d6f330d58755007dbfe9d14fb4a5 xvfb-run --auto-servernum --server-args="-screen 0 1024x768x24" python3 main.py
