#!/bin/bash
#PBS -l nodes=1:ppn=1
#PBS -l mem=32gb
#PBS -l walltime=12:00:00
set -e

# Make output directory
mkdir -p out_dir
mkdir -p html_report

# Prevent from creating too many threads to avoid an Out Of Memory (OOM) error in Brainlife
export OMP_NUM_THREADS=1
export OPENBLAS_NUM_THREADS=1
export MKL_NUM_THREADS=1
export NUMEXPR_NUM_THREADS=1
export VECLIB_MAXIMUM_THREADS=1
export SINGULARITYENV_OMP_NUM_THREADS=1
export SINGULARITYENV_OPENBLAS_NUM_THREADS=1
export SINGULARITYENV_MKL_NUM_THREADS=1
export SINGULARITYENV_NUMEXPR_NUM_THREADS=1
export SINGULARITYENV_VECLIB_MAXIMUM_THREADS=1
export SINGULARITY_DOCKER_INSECURE=1
export GODEBUG=http2client=0

# Own image (uploaded to GitHub)
singularity exec -e docker://ghcr.io/carlota-juarez/app-mne-bids:full python3 main.py